kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "app1-pipeline"
spec:
  source:
    type: "Git"
    git:
      uri: "https://github.com/wohshon/pipeline-build"
      ref: "ocp3-demo"
  strategy:
    type: "JenkinsPipeline"
    jenkinsPipelineStrategy:
      jenkinsfilePath: jenkinfile
